---

collections:
- name: https://opendev.org/openstack/ansible-collections-openstack
  version: 9f3f0837c88f847b229e8bcd23986b362eee9b1f
  type: git
- name: https://opendev.org/openstack/ansible-config_template
  version: 2.0.0
  type: git
- name: https://opendev.org/openstack/openstack-ansible-plugins
  version: master
  type: git
- name: https://github.com/ansible-collections/community.general
  version: 5.6.0
  type: git
- name: https://github.com/ansible-collections/community.rabbitmq
  version: 1.2.2
  type: git
- name: https://github.com/ansible-collections/community.mysql
  version: 3.5.1
  type: git
- name: https://github.com/ansible-collections/community.crypto
  version: 2.7.0
  type: git
- name: https://github.com/ansible-collections/ansible.posix
  version: 1.4.0
  type: git
- name: https://github.com/gluster/gluster-ansible-collection
  version: 1.0.2
  type: git
# NOTE(noonedeadpunk): needs version in galaxy.yml to pull from git
- name: ansible.netcommon
  version: 3.1.1
  source: https://galaxy.ansible.com
- name: ansible.utils
  version: 2.6.1
  source: https://galaxy.ansible.com
- name: openvswitch.openvswitch
  version: 2.1.0
  source: https://galaxy.ansible.com
