- name: Filling skeleton inventory
  hosts: localhost
  tasks:
    - import_tasks: tasks/generate_dynamic_inventory.yml

- name: Deploying Galera cluster
  hosts: galera_all
  become_method: sudo
  roles:
    - name: galera_server
      become: yes
      vars:
        galera_install_server: true
        galera_server_bind_address: 0.0.0.0

- name: Deploying RabbitMQ cluster
  hosts: rabbitmq_all
  become_method: sudo
  roles:
    - name: rabbitmq_server
      become: yes
  vars:
    openstack_pki_setup_host: "{{ groups['rabbitmq_all'][0] }}"

- name: Installing memcached
  hosts: memcached
  become_method: sudo
  roles:
    - name: memcached_server
      become: yes

- import_playbook: utility-install.yml
- import_playbook: certificate-ssh-authority.yml

- name: Installing Keystone
  hosts: keystone_all
  become: yes
  pre_tasks:
    - name: "Pre-service deployment tasks from os_keystone role"
      include_role:
        name: os_keystone
        tasks_from: main_pre.yml
      vars:
        keystone_ssh_keypairs_setup_host: "{{ groups['keystone_all'][0] }}"
  roles:
    - name: os_keystone
  vars:
    keystone_user_pip_packages:
      - python-binary-memcached
  vars_files:
    - "defaults/{{ install_method }}_install.yml"

- name: Installing Glance
  hosts: glance_all
  roles:
    - name: os_glance
      become: yes
  vars_files:
    - "defaults/{{ install_method }}_install.yml"
  tags:
    - glance

- name: Installing Placement
  hosts: placement_all
  roles:
    - name: os_placement
      become: yes
  vars_files:
    - "defaults/{{ install_method }}_install.yml"

- name: Installing Nova control plane
  import_playbook: install-nova.yml
  vars:
    nova_hosts: "nova_conductor:nova_scheduler:nova_api_os_compute:nova_api_metadata:nova_console"

- name: Install Neutron API server
  import_playbook: install-neutron.yml
  vars:
    neutron_hosts: "neutron_server"
    venv_wheel_build_enable: False

- name: Install Neutron agents
  import_playbook: install-neutron.yml
  vars:
    neutron_hosts: "neutron_dhcp_agent:neutron_metadata_agent"
    venv_wheel_build_enable: False

- name: Install Neutron L2 agents
  import_playbook: install-neutron.yml
  vars:
    neutron_hosts: "neutron_linuxbridge_agent"
    venv_wheel_build_enable: False

- name: Install cinder scheduler services
  import_playbook: install-cinder.yml
  vars:
    cinder_hosts: "cinder_scheduler"
    cinder_serial: "{{ cinder_scheduler_serial | default(['1', '100%']) }}"

- name: Install cinder volume services
  import_playbook: install-cinder.yml
  vars:
    cinder_hosts: "cinder_volume"
    cinder_serial: "{{ cinder_backend_serial | default(['1', '100%']) }}"

- name: Install cinder API services
  import_playbook: install-cinder.yml
  vars:
    cinder_hosts: "cinder_api"
    cinder_serial: "{{ cinder_api_serial | default(['1', '100%']) }}"
