- name: Generating in-memory inventory
  hosts: localhost
  gather_facts: yes
  tasks:
    - import_tasks: tasks/generate_dynamic_inventory.yml

- name: Installing StorPool
  hosts: storpool
  gather_facts: yes
  pre_tasks:
    - import_tasks: tasks/generate_storpool_configuration.yml
  roles:
    - storpool.bootstrap_node
    - storpool.install_sp_python
    - name: storpool.install_storpool_components
      vars:
        sp_configuration_path: "{{ storpool_temp_configuration.path }}"
    - storpool.configure_networking

- name: Configure StorPool disks
  hosts: storpool_server
  gather_facts: no
  roles:
    - storpool.initialize_disks

- name: Configure StorPool CGroups
  hosts: storpool
  gather_facts: no
  roles:
    - storpool.configure_cgroups
    - storpool.configure_services

