- name: Bootstraping OpenStack control plane hosts
  hosts: openstack_controllers
  become_method: sudo
  roles:
    - name: openstack_hosts
      become: yes
      vars:
        openstack_host_manage_deploy_hosts_file: no

- name: Deploying Galera cluster
  hosts: galera_all
  become_method: sudo
  roles:
    - name: galera_server
      become: yes
      vars:
        galera_install_server: true

- name: Deploying RabbitMQ cluster
  hosts: rabbitmq_all
  become_method: sudo
  roles:
    - name: rabbitmq_server
      become: yes
  vars:
    openstack_pki_setup_host: "{{ groups['rabbitmq_all'][0] }}"

- name: Installing memcached
  hosts: memcached
  become_method: sudo
  roles:
    - name: memcached_server
      become: yes

- import_playbook: utility-install.yml
- import_playbook: certificate-ssh-authority.yml

- name: Installing Keystone
  hosts: keystone_all
  become_method: sudo
  roles:
    - name: os_keystone
      become: yes
  vars_files:
    - "defaults/repo_packages/openstack_services.yml"
    - "defaults/{{ install_method }}_install.yml"
