plugin: openstack.cloud.openstack
legacy_groups: no
expand_hostvars: yes
fail_on_errors: yes
compose:
  management_address: openstack.access_ipv4
  tunnel_address: openstack.access_ipv4
  storage_address: openstack.access_ipv4
keyed_groups:
  - key: openstack.metadata.os_dev_stack_uuid
    prefix: os_dev_stack
  - key: openstack.metadata.os_dev_stack_role
    prefix: os_dev_stack
