all:
  hosts:
  children:
    hosts:
      hosts:
      children:
        openstack_hosts:
          hosts:
          children:
            galera_all:
              hosts:
            qdrouterd_all:
              hosts:
            rabbitmq_all:
              hosts:
            memcached:
              hosts:
            utility_all:
              hosts:
            keystone_all:
              hosts:
              vars:
            glance_all:
              hosts:
              children:
                glance_api:
                  hosts:
              vars:
                glance_user_pip_packages:
                  - storpool
                  - storpool.spopenstack
            placement_all:
              hosts:
              children:
                placement_api:
                  hosts:
            nova_all:
              hosts:
              children:
                nova_api_os_compute:
                  hosts:
                nova_api_metadata:
                  hosts:
                nova_conductor:
                  hosts:
                nova_scheduler:
                  hosts:
                nova_console:
                  hosts:
                nova_compute:
                  hosts:
              vars:
                nova_libvirtd_listen_tls: 0
                nova_qemu_vnc_tls: 0
                nova_user_pip_packages:
                  - storpool
                  - storpool.spopenstack
            neutron_all:
              hosts:
              children:
                neutron_server:
                  hosts:
                neutron_dhcp_agent:
                  hosts:
                neutron_metadata_agent:
                  hosts:
                neutron_linuxbridge_agent:
                  hosts:
                neutron_l3_agent:
                  hosts:
                neutron_ovn_northd:
                  hosts:
              vars:
                neutron_provider_networks:
                  network_types: "vxlan,flat"
                  network_flat_networks: "provider"
                neutron_neutron_conf_overrides:
                  experimental:
                    linuxbridge: True
            cinder_all:
              hosts:
              children:
                cinder_api:
                  hosts:
                cinder_scheduler:
                  hosts:
                cinder_volume:
                  hosts:
                cinder_backup:
                  hosts:
              vars:
                cinder_glance_api_servers: "http://{{ groups['utility_all'][0] }}:9292"
                cinder_user_pip_packages:
                  - storpool
                  - storpool.spopenstack
                cinder_backends:
                  storpool_virtual:
                    volume_backend_name: storpool_virtual
                    volume_driver: cinder.volume.drivers.storpool.StorPoolDriver
                    storpool_template: virtual
                    iscsi_portal_group: pg
                    iscsi_cinder_volume: True
    storpool:
      hosts:
      vars:
        sp_new_cluster: True
        sp_reboot_after_install: True
        sp_cg_conf_extra: system_limit=2G user_limit=1G
      children:
        storpool_server:
          hosts:
          vars:
            sp_min_disk_size: 200GB
            sp_test_discovered_disks: False
        storpool_block:
          hosts:
        storpool_mgmt:
          hosts:
        storpool_iscsi:
          hosts:
  vars:
    openstack_ssh_keypairs_setup_host: "{{ groups['utility_all'][0] }}"
    external_lb_vip_address: "{{ hostvars[groups['utility_all'][0]]['management_address'] }}"
    internal_lb_vip_address: "{{ hostvars[groups['utility_all'][0]]['management_address'] }}"
    galera_root_user: root
