- name: Creating a temporary file
  delegate_to: localhost
  ansible.builtin.tempfile:
  register: storpool_temp_configuration

- name: Rendering StorPool configuration template
  delegate_to: localhost
  ansible.builtin.template:
    src: templates/storpool.conf.j2
    dest: "{{ storpool_temp_configuration['path'] "
